### ISSUE TITLE
hi,I have a problem about dronedataset.

### ISSUE THREAD

**Issue by BruceHe453** [Al-Sad/DDI_Software#1]
USRP receive IQ data,so data=I+jQ is complex signal.But dronedataset is real number,only save real data?

**Comment by Al-Sad** [comment]
We save the magnitude \sqrt{ I^2 + Q^2}

**Comment by ltindall** [comment]
For anybody that comes across this thread: 
I don't think the data is magnitude \sqrt{ I^2 + Q^2} because it contains negative values. 
Rather, I think it is the signal voltage x(t) = I cos(2 * pi * f * t) + Q sin(2 * pi * f * t)
