### ISSUE TITLE
Level 3 classes

### ISSUE THREAD

**Issue by ksohan** [Al-Sad/DDI_Software#5]
What are the classes/labels of the level 3 dataset?
In the [Classification.py](https://github.com/Al-Sad/DroneRF/blob/master/Python/Classification.py) file,
```
Label_3 = np.transpose(Data[2050:2051,:]); Label_3 = Label_3.astype(int);
y = encode(Label_3)

print(y.shape)
```
This outputs `(22700, 10)`, so based on this there are 10 classes. But according to this image from the paper, it seems there should be 12.
![image](https://github.com/Al-Sad/DroneRF/assets/25526072/250851bd-a373-4848-b75a-0f1b8bcf217d)

Can you please clarify this? And also mentions the labels/classes?

Thank you

**Comment by ksohan** [comment]
@Al-Sad Kindly clarify this

**Comment by Al-Sad** [comment]
Hello. The figure you are referring to explains the data labeling protocol and not the collected data. This is important for other studies to produce datasets with similar collection/labeling standards. The collected data is detailed in Table 4 of the corresponding paper and has the following level 3 labels: Bebop mode 1, Bebop mode 2, Bebop mode 3, Bebop mode 4, AR mode 1, AR mode 2, AR mode 3, AR mode 4, Phantom mode 1, and No Drone.
Please refer to the papers for more details.
https://www.sciencedirect.com/science/article/abs/pii/S0167739X18330760?fr=RR-1&ref=cra_js_challenge
https://www.sciencedirect.com/science/article/pii/S2352340919306675
